/**
 * Auto-generated by `supabase gen types typescript` (via Supabase MCP).
 * Re-run after schema changes: see scripts/regenerate-types.sh (Phase 3).
 */
export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  __InternalSupabase: {
    PostgrestVersion: "14.5"
  }
  public: {
    Tables: {
      appointments: {
        Row: {
          address: string | null
          caller_name: string
          caller_phone: string
          created_at: string
          id: string
          issue: string
          slot_end: string
          slot_start: string
          status: string
          technician_id: string
          technician_name: string
          urgency: string
          vertical_id: string
        }
        Insert: {
          address?: string | null
          caller_name: string
          caller_phone: string
          created_at?: string
          id?: string
          issue: string
          slot_end: string
          slot_start: string
          status?: string
          technician_id: string
          technician_name: string
          urgency: string
          vertical_id: string
        }
        Update: {
          address?: string | null
          caller_name?: string
          caller_phone?: string
          created_at?: string
          id?: string
          issue?: string
          slot_end?: string
          slot_start?: string
          status?: string
          technician_id?: string
          technician_name?: string
          urgency?: string
          vertical_id?: string
        }
        Relationships: []
      }
    }
    Views: { [_ in never]: never }
    Functions: { [_ in never]: never }
    Enums: { [_ in never]: never }
    CompositeTypes: { [_ in never]: never }
  }
}
